# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 03:31
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='WBText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=500, verbose_name='微博')),
            ],
        ),
        migrations.CreateModel(
            name='WBUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='昵称')),
                ('gender', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女'), (3, '其他')], default=0, verbose_name='性别')),
                ('_info', models.TextField(blank=True, null=True, verbose_name='其他信息')),
                ('followers', models.ManyToManyField(to='weibo.WBUser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WeiBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weibos', to='weibo.WBText', verbose_name='文本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weibos', to='weibo.WBUser', verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='wbtext',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weibo.WBUser', verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weibo.WBText', verbose_name='被评信息'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weibo.WBText', verbose_name='评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weibo.WBUser', verbose_name='用户'),
        ),
    ]
