# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbtext',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ori_wbs', to='weibo.WBUser', verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs', to='weibo.WBText', verbose_name='文本'),
        ),
        migrations.AlterField(
            model_name='weibo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs', to='weibo.WBUser', verbose_name='用户'),
        ),
    ]
